version: 1.0
stages:
  - stage1
  - stage2
  - stage3
  - stage4
jobs:
  job1:
    description: source cloning job
    type: source-checkout
    stage: stage1
    timeout: 30
    priority: major
    parameters:
      branch: main
  job3:
    description: source cloning job
    type: source-checkout
    stage: stage1
    timeout: 30
    priority: major
    parameters:
      branch: main
  job2:
    description: source cloning job
    type: source-checkout
    stage: stage2
    timeout: 30
    priority: major
    parameters:
      branch: main
  job4:
    description: source cloning job
    type: source-checkout
    stage: stage2
    timeout: 30
    priority: major
    parameters:
      branch: main
  job5:
    description: source cloning job
    type: source-checkout
    stage: stage3
    timeout: 30
    priority: major
    parameters:
      branch: main
  job6:
    description: source cloning job
    type: source-checkout
    stage: stage4
    timeout: 30
    priority: major
    parameters:
      branch: main
  job7:
    description: source cloning job
    type: source-checkout
    stage: stage4
    timeout: 30
    priority: major
    parameters:
      branch: main
