version: 1.0
agentTags:
- tag1
stages:
- stage1
jobs:
  job1:
    description: source cloning job
    type: source-checkout
    stage: stage1
    timeout: 30
    priority: major
    parameters:
      branch: main
