version: 1.0
stages:
  stage1:
    jobs:
    - - antgithub
    stageTransition:
      movement: approval
      timeLimit: 10
      priority: skip
      approvers:
      - navinkumar.br+cmdev_2@zohotest.com
      pattern: (1|2)
      exclusionCriteria:
      - type: all_job_success
      - type: cron
        triggerName: crontrigger

  stage2:
    jobs:
    - - antgithub1
    stageTransition:
      movement: approval
      timeLimit: 15
      priority: skip
      approvers:
      - navinkumar.br+cmdev_2@zohotest.com
      pattern: (1)
      exclusionCriteria:
      - type: cron
        triggerName: crontrigger

  stage3:
    jobs:
    - - antgithub2
    stageTransition:
      movement: approval
      timeLimit: 25
      priority: stop
      approvers:
      - navinkumar.br+cmdev_2@zohotest.com
      pattern: (1)
      exclusionCriteria:
      - type: cron
        triggerName: crontrigger

  stage4:
    jobs:
    - - antgithub3
   
jobs:
  antgithub:
    description: source cloning job
    type: source-checkout
    timeout: 30
    parameters:
      service: github
      integration: github_Navin-03
      repo: github_cmdev_1
      branch: main
  antgithub1:
    description: source cloning job
    type: source-checkout
    timeout: 30
    parameters:
      service: github
      integration: github_Navin-03
      repo: github_cmdev_1
      branch: main
  antgithub2:
    description: source cloning job
    type: source-checkout
    timeout: 30
    parameters:
      service: github
      integration: github_Navin-03
      repo: github_cmdev_1
      branch: main
  antgithub3:
    description: source cloning job
    type: source-checkout
    timeout: 30
    parameters:
      service: github
      integration: github_Navin-03
      repo: github_cmdev_1
      branch: main